/*CREANDO LA BASE DE DATOS REAL_TIME_DATA*/

USE master
GO

IF EXISTS(SELECT NAME FROM SYS.databases WHERE NAME='REAL_TIME_DATA')
BEGIN
	DROP DATABASE REAL_TIME_DATA
END
GO

/*CREANDO BASE DE DATOS*/
CREATE DATABASE REAL_TIME_DATA
GO

USE REAL_TIME_DATA
GO


SET ANSI_NULLS ON /*CONTROL Y MANEJO CORRECTO DE LOS VALORES NULL EN LAS COMPARACIONES*/
GO

SET QUOTED_IDENTIFIER ON /*PERMITE NOMBRES DE OBJETOS MAS FLEXIBLES Y EVITA PROBLEMAS CON PALABRAS RESERVADAS*/
GO

/*CREANDO TABLA DONDE SE GUARDARAN LOS DATOS DEL API*/
CREATE TABLE WeatherData (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    City NVARCHAR(100),
    Country NVARCHAR(100),
    Temperature decimal(10,2),
    Humidity INT,
    Pressure INT,
    WindSpeed decimal(10,2),
    WeatherDescription NVARCHAR(200),
    Timestamp DATETIME DEFAULT GETDATE()
);

/*QUERY PARA INSERCIÓN DE DATOS*/
INSERT INTO  WeatherData (City,Country,Temperature,Humidity,Pressure,WindSpeed,WeatherDescription)
VALUES (?,?,?,?,?,?,?)


/*CONSULTANDO DATOS*/
SELECT * FROM WeatherData
